import os
import time
from typing import Optional

import click
import matplotlib.pyplot as plt
import torch

from advsecurenet.dataloader import DataLoaderFactory
from advsecurenet.shared.types.attacks import AttackType
from advsecurenet.shared.types.configs import ConfigType, attack_configs
from advsecurenet.utils.config_utils import get_default_config_yml
from cli.attacks.lots import CLILOTSAttack
from cli.utils.attack import execute_attack
from cli.utils.config import build_config, load_configuration
from cli.utils.data import load_and_prepare_data
from cli.utils.model import prepare_model

# Mapping of attack types to their respective configurations
attack_mapping = {
    "CW": (AttackType.CW, attack_configs.CWAttackConfig),
    "DEEPFOOL": (AttackType.DEEPFOOL, attack_configs.DeepFoolAttackConfig),
    "PGD": (AttackType.PGD, attack_configs.PgdAttackConfig),
    "FGSM": (AttackType.FGSM, attack_configs.FgsmAttackConfig),
    "TARGETED_FGSM": (AttackType.TARGETED_FGSM, attack_configs.FgsmAttackConfig),
    "LOTS": (AttackType.LOTS, attack_configs.LotsAttackConfig),
    "DECISION_BOUNDARY": (AttackType.DECISION_BOUNDARY, attack_configs.DecisionBoundaryAttackConfig),
}


def cli_attack(attack_name: str, config: str, **kwargs):
    """Execute a specified attack."""
    if attack_name not in attack_mapping:
        raise ValueError(f"Unknown attack type: {attack_name}")

    attack_type, attack_config_class = attack_mapping[attack_name]
    cli_execute_general_attack(
        attack_type, config, attack_config_class, **kwargs)


def cli_execute_general_attack(attack_type, config_file: str, attack_config_class, **kwargs) -> None:
    """
    The logic function to execute an attack based on the attack type.
    """
    attack_name = attack_type.name.lower()
    if not config_file:
        click.secho(
            f"No config file provided! Using default {attack_name} attack config.", fg="yellow")

        file_name = f'{attack_name}_attack_config.yml'
        config_file = get_default_config_yml(file_name, "cli")

    config_data = load_configuration(
        config_type=ConfigType.ATTACK, config_file=config_file, **kwargs)

    if attack_type == AttackType.LOTS:
        click.echo(f"Executing {attack_name} attack...")
        attack = CLILOTSAttack(config_data)
        adversarial_images = attack.execute_attack()

    else:
        if attack_type == AttackType.CW and config_data['targeted']:
            click.UsageError(
                "Targeted CW attack through CLI not supported yet! Please set targeted to False or use API.")
        data, num_classes, device = load_and_prepare_data(config_data)
        attack_config = build_config(config_data, attack_config_class)

        model = prepare_model(config_data, num_classes, device)

        attack_class = attack_type.value  # Get the class from the Enum
        attack = attack_class(attack_config)
        click.echo(f"Executing {attack_name} attack...")

        data_loader = DataLoaderFactory.create_dataloader(
            data, batch_size=config_data['batch_size'])

        adversarial_images = execute_attack(
            model=model, data_loader=data_loader, attack=attack, device=device, verbose=config_data['verbose'])

        if config_data['save_result_images']:
            save_adversarial_images(
                data,
                adversarial_images,
                attack_name,
                config_data['save_limit'],
                config_data['result_images_dir']
            )


def save_adversarial_images(original_images: torch.utils.data.TensorDataset,
                            adversarial_images: list[torch.Tensor],
                            attack_name: str,
                            save_limit: Optional[int] = 10,
                            save_dir: Optional[str] = None
                            ) -> None:
    """ 
    Saves the adversarial images generated by the attack in a folder. 
    The folder is named after the attack and contains a folder for each sample. 
    The folder for each sample contains the original image and the adversarial image.

    Args:
        original_images (torch.utils.data.TensorDataset): The original images.
        adversarial_images (list[torch.Tensor]): The adversarial images.
        attack_name (str): The name of the attack.
        save_limit (Optional[int]): The number of images to save. If -1 or None, all images are saved. Defaults to 10.
        save_dir (Optional[str]): The directory to save the images in. Defaults to None.
    """
    # save_dir is the current directory + attack name + current time
    current_time = time.strftime("%Y%m%d-%H%M%S")
    save_dir = os.path.join(os.getcwd(), attack_name +
                            "_" + current_time) if save_dir is None else save_dir
    create_directory(save_dir)

    # Flatten the list of adversarial images
    adversarial_images_list = [
        adv_image for adv_images in adversarial_images for adv_image in adv_images]

    # Determine the number of images to save
    total_images = len(original_images)
    save_all = save_limit is None or save_limit == -1 or save_limit > total_images
    save_limit = total_images if save_all else save_limit

    for i in range(save_limit):
        # Sequentially save images if save_all, else randomly select
        idx = i if save_all else torch.randint(0, total_images, (1,)).item()

        # Create a folder for each pair of images and save them
        folder = os.path.join(save_dir, f"sample_{i}")
        create_directory(folder)

        # Save the original and adversarial images
        save_image(original_images[idx][0],
                   os.path.join(folder, "original.png"))
        save_image(adversarial_images_list[idx], os.path.join(
            folder, "adversarial.png"))

    print(f"Adversarial images saved in {save_dir}")


def create_directory(path: str):
    """Create a directory if it doesn't exist."""
    if not os.path.exists(path):
        os.makedirs(path)


def save_image(image: torch.Tensor, path: str):
    """Save a tensor image to a specified path."""
    plt.imsave(path, image.squeeze().cpu().numpy())
