# Description: The configuration file for adversarial training.

training: !include ../train_test/train_config.yml # Training configuration file.

adversarial_training:
  # --- Target Model and Attack Configurations ---
  models: null # List of models used for generating adversarial examples.
  attacks: # List of attacks used for generating adversarial examples.
    - attack1: config_file.yml
