import os
import time
from typing import Optional

import torch
from tqdm.auto import tqdm

from advsecurenet.attacks import AdversarialAttack
from advsecurenet.dataloader import DataLoaderFactory
from advsecurenet.models.base_model import BaseModel
from cli.utils.helpers import create_directory, save_image


def execute_attack(model: BaseModel,
                   data_loader: DataLoaderFactory,
                   attack: AdversarialAttack,
                   device: torch.device = torch.device("cpu"),
                   verbose: bool = False
                   ) -> list[torch.Tensor]:
    try:
        model.eval()
        adversarial_images = []
        for images, labels in tqdm(data_loader, desc="Generating adversarial samples", disable=not verbose):
            images = images.to(device)
            labels = labels.to(device)
            # Generate adversarial images
            adv_images = attack.attack(model, images, labels)
            adversarial_images.append(adv_images)

        return adversarial_images
    except Exception as e:
        print("Error occurred while executing attack!")
        raise e


def save_adversarial_images(original_images: torch.utils.data.TensorDataset,
                            adversarial_images: list[torch.Tensor],
                            attack_name: str,
                            save_limit: Optional[int] = 10,
                            save_dir: Optional[str] = None
                            ) -> None:
    """ 
    Saves the adversarial images generated by the attack in a folder. 
    The folder is named after the attack and contains a folder for each sample. 
    The folder for each sample contains the original image and the adversarial image.

    Args:
        original_images (torch.utils.data.TensorDataset): The original images.
        adversarial_images (list[torch.Tensor]): The adversarial images.
        attack_name (str): The name of the attack.
        save_limit (Optional[int]): The number of images to save. If -1 or None, all images are saved. Defaults to 10.
        save_dir (Optional[str]): The directory to save the images in. Defaults to None.
    """
    # save_dir is the current directory + attack name + current time
    current_time = time.strftime("%Y%m%d-%H%M%S")
    save_dir = os.path.join(os.getcwd(), attack_name +
                            "_" + current_time) if save_dir is None else save_dir
    create_directory(save_dir)

    # Flatten the list of adversarial images
    adversarial_images_list = [
        adv_image for adv_images in adversarial_images for adv_image in adv_images]

    # Determine the number of images to save
    total_images = len(original_images)
    save_all = save_limit is None or save_limit == -1 or save_limit > total_images
    save_limit = total_images if save_all else save_limit

    for i in range(save_limit):
        # Sequentially save images if save_all, else randomly select
        idx = i if save_all else torch.randint(0, total_images, (1,)).item()

        # Create a folder for each pair of images and save them
        folder = os.path.join(save_dir, f"sample_{i}")
        create_directory(folder)

        # Save the original and adversarial images
        save_image(original_images[idx][0],
                   os.path.join(folder, "original.png"))
        save_image(adversarial_images_list[idx], os.path.join(
            folder, "adversarial.png"))

    print(f"Adversarial images saved in {save_dir}")
